### ISSUE TITLE
Требуется актуализация

### ISSUE THREAD

**Issue by ArtJapp** [Maksim2355/IntuitiveProgramming#4]
Данный свод правил отстает от современных трендов разработки, а потому **нуждается** в поддержке и расширении. 

В частности, не отражен пласт смехуёчков про КЕГУ, а это важно!
<img width="450" src="https://github.com/Maksim2355/IntuitiveProgramming/assets/13205442/2f3283a8-8207-40fd-b701-34b919f12efc">

Кроме того, чтобы при разработке не случились военные преступления, необходимо помнить Принцип Шлёпы
<img width="450" src="https://github.com/Maksim2355/IntuitiveProgramming/assets/13205442/009e5351-4d86-40fc-bf33-a48bffb9852c">

Прошу учесть вышеизложенные замечания при подготовке нового издания правил интуитивного программирования
<img width="250" src="https://github.com/Maksim2355/IntuitiveProgramming/assets/13205442/832d803c-233b-48c3-9d55-e4215b7c6121">

**Comment by Maksim2355** [comment]
Это не военное преступление, если тебе было смешно
